Repository fga-eps-mds/2022-1-schedula-front, pull requests merged in 2022-09, with the labels that each got.

#61 23 criar editar posto de trabalho
  .env.development
  src/components/Forms/WorkstationForm/index.tsx
  src/pages/workstation/index.tsx
  src/routes/index.tsx
  src/services/Workstation/Workstation.d.ts
  src/services/Workstation/index.ts
Labels: Feature, MDS

#72 Refactor chamado form
  src/components/ActionButtons/index.tsx
  src/components/Datepicker/index.tsx
  src/components/Footnote/ServicesStatus.tsx
  src/components/Footnote/useServicesData.tsx
  src/components/Forms/ChamadoForm/ChamadoForm.d.ts
  src/components/Forms/ChamadoForm/ChamadoFormWrapper.tsx
  src/components/Forms/ChamadoForm/EventForm.tsx
  src/components/Forms/ChamadoForm/helpers.ts
  src/components/Forms/ChamadoForm/index.tsx
  src/components/Modal/Modal.tsx
  src/components/RefreshButton/index.tsx
  src/constants/Chamados/index.tsx
  src/pages/chamados/index.tsx
  src/services/Chamados/Chamados.d.ts
  src/utils/formatDate.ts
Labels: enhancement, EPS

#73 Add multi select to ProblemType input
  src/components/ControlledSelect/index.tsx
  src/components/Forms/ChamadoForm/ChamadoForm.d.ts
  src/components/Forms/ChamadoForm/helpers.ts
  src/components/Forms/ChamadoForm/index.tsx
  src/pages/chamados/index.tsx
  src/pages/chamados/registrar.tsx
Labels: enhancement, EPS

#78 Fix edit workstation
  .env.development
  src/components/Forms/WorkstationForm/WorkstationPageForm/index.tsx
  src/components/Forms/WorkstationForm/index.tsx
  src/pages/workstation/index.tsx
Labels: enhancement, MDS

#79 68 acesso cidades
  src/pages/cidades/index.tsx
  src/pages/usuarios/index.tsx
Labels: Feature, MDS
