Repository fga-eps-mds/2022-1-schedula-front, pull requests merged in 2022-08, with the labels that each got.

#18 #8-criar_e_editar_categoria_de_problema
  src/components/ItemCategory.tsx
  src/components/ModalCadCategory.tsx
  src/components/ModalEditCategory.tsx
  src/pages/ListaCategoria.tsx
  src/pages/_app.tsx
  src/pages/listaCategoria.tsx
  src/services/testApi.ts
Labels: Feature, MDS

#19 Criar código de conduta
  CODE_OF_CONDUCT.md
Labels: documentation, EPS

#32 #25 Página de Listagem De Cidades
  .eslintrc.json
  src/components/DashboardOptions.tsx
  src/components/ItemCategory.tsx
  src/components/ListIcon.tsx
  src/components/ListItem.tsx
  src/components/ListagemBody.tsx
  src/components/ListagemButtonCad.tsx
  src/components/ListagemHeader.tsx
  src/components/ModalCad&Edit.tsx
  src/components/ModalDel.tsx
  src/components/ModalDelCategory.tsx
  src/components/ModalDelType.tsx
  src/components/ModalEditCategory.tsx
  src/components/SideBar/index.tsx
  src/components/loading.tsx
  src/pages/ListaCategoria.tsx
  src/pages/listaCategoria.tsx
  src/pages/listaCidades.tsx
  src/pages/teste.tsx
  src/services/DataType.ts
  src/services/FunctionList.ts
  src/services/RequestCad.ts
  src/services/RequestDel.ts
  src/services/RequestEdit.ts
  src/services/testApi.ts
Labels: Feature, MDS

#37 Add external analyzer to sonarcloud pipeline
  .github/workflows/ci.yml
  README.md
  reports/eslint-report.json
  sonar-project.properties
Labels: devops, analytics, EPS

#36 #26 & 27 criar, editar, excluir cidades.
  src/components/CategoriaTipos/FunctionList.ts
  src/components/CategoriaTipos/ListIcon.tsx
  src/components/CategoriaTipos/ListItem.tsx
  src/components/CategoriaTipos/ListagemButtonCad.tsx
  src/components/CategoriaTipos/ModalCad&Edit.tsx
  src/components/CategoriaTipos/ModalDel.tsx
  src/components/CategoriaTipos/RequestCad.ts
  src/components/CategoriaTipos/RequestEdit.ts
  src/components/Cidades/FunctionList.ts
  src/components/Cidades/ListIcon.tsx
  src/components/Cidades/ListItem.tsx
  src/components/Cidades/ListagemButtonCad.tsx
  src/components/Cidades/ModalCad&Edit.tsx
  src/components/Cidades/ModalDel.tsx
  src/components/Cidades/Request.ts
  src/components/DataType.ts
  src/pages/listaCategoria.tsx
  src/pages/listaCidades.tsx
  src/services/RequestDel.ts
  src/services/RequestEdit.ts
Labels: Feature, MDS

#40 Add category name to the problem type page
  src/components/PageHeader.tsx
  src/components/RefreshButton/index.tsx
  src/components/SideBar/index.tsx
  src/pages/categorias/[id]/problemas.tsx
  src/pages/categorias/index.tsx
  src/pages/usuarios/index.tsx
  src/services/DetalhadorChamados/index.ts
  src/styles/ColorTheme.ts
Labels: enhancement

#46 Add pre-push hook to run test suite
  .github/workflows/ci.yml
  .husky/pre-push
  .prettierrc.json
  .vscode/settings.json
  next.config.js
  package.json
  src/components/SideBar/Sidebar.spec.tsx
  src/pages/usuarios/index.tsx
  yarn.lock
Labels: enhancement, devops, EPS

#48 42 cidades
  .env
  src/components/Forms/CidadeForm/index.tsx
  src/hooks/useRequest.ts
  src/pages/cidades/index.tsx
  src/routes/index.tsx
  src/services/Cidades/Cidades.d.ts
  src/services/Cidades/index.ts
  src/services/DetalhadorChamados/DetalhadorChamados.d.ts
  src/services/DetalhadorChamados/DetalhadosChamados.d.ts
  src/services/api.ts
Labels: Feature, MDS

#54 Code split ListItemActions
  src/components/ActionButtons/ActionButton.d.ts
  src/components/ActionButtons/AddButton/index.tsx
  src/components/ActionButtons/DeleteButton/index.tsx
  src/components/ActionButtons/EditButton/index.tsx
  src/components/ActionButtons/index.tsx
  src/components/Footnote/ServicesStatus.tsx
  src/components/Footnote/index.tsx
  src/components/Footnote/useServicesData.tsx
  src/components/List/List.spec.tsx
  src/components/List/index.tsx
  src/components/ListItem/ListItem.spec.tsx
  src/components/ListItem/ListItemActions/ListItemActions.spec.tsx
  src/components/ListItem/ListItemActions/index.tsx
  src/components/ListItem/index.tsx
  src/pages/categorias/[id]/problemas.tsx
  src/pages/categorias/index.tsx
  src/pages/cidades/index.tsx
  src/pages/usuarios/index.tsx
  src/pages/workstation/index.tsx
Labels: enhancement

#65 Cadastro de Eventos
  .env.development
  package.json
  src/components/ActionButtons/DeleteButton/index.tsx
  src/components/ControlledSelect/index.tsx
  src/components/Datepicker/index.tsx
  src/components/Footnote/ServicesStatus.tsx
  src/components/Footnote/useServicesData.tsx
  src/components/Forms/CategoriaForm/index.tsx
  src/components/Forms/ChamadoForm/ChamadoForm.d.ts
  src/components/Forms/ChamadoForm/ChamadoFormWrapper.tsx
  src/components/Forms/ChamadoForm/helpers.ts
  src/components/Forms/ChamadoForm/index.tsx
  src/components/Forms/ChamadoForm/useDropdowData.tsx
  src/components/ListItem/index.tsx
  src/components/Modal/Modal.tsx
  src/constants/Chamados/index.tsx
  src/pages/categorias/[id]/problemas.tsx
  src/pages/categorias/index.tsx
  src/pages/chamados/index.tsx
  src/pages/chamados/registrar.tsx
  src/pages/cidades/index.tsx
  src/services/Categorias/Categoria.d.ts
  src/services/Categorias/index.ts
  src/services/Chamados/Chamados.d.ts
  src/services/Chamados/index.tsx
  src/services/Cidades/index.ts
  src/services/Problemas/index.ts
  src/services/Usuarios/index.ts
  src/services/Workstation/index.ts
  src/services/index.ts
  src/services/result.d.ts
  src/services/types.d.ts
  src/styles/Colors.ts
  src/styles/theme.ts
  yarn.lock
Labels: enhancement, EPS
